apiVersion: v1
kind: Pod
metadata:
  name: helloworld
  labels:
    environment: production
    app: nginx
    demo: "true"
spec:
  containers:
  - name: helloworld
    image: ubuntu:latest
    # Just spin & wait forever
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
